[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['cd server && npm ci --production']

[phases.build]
cmds = []

[start]
cmd = 'cd server && node server.js'
